/*
 * This file was generated by the Gradle "init" task.
 */

dependencies{
    implementation(project(":spring-boot-ktor"))
    implementation("org.springframework.boot:spring-boot-starter:2.5.4")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30")
    testImplementation("org.jetbrains.kotlin:kotlin-test:1.3.30")
}

group = "com.theoxao"
version = "1.0-SNAPSHOT"
description = "simple_example"
java.sourceCompatibility = JavaVersion.VERSION_1_8
